import { expect, test, type Locator, type Page } from '@playwright/test'

const endpoint = process.env.WORKSPACE_LIVE_API
// 真实 Key 只在本次页面验证中使用，不写入浏览器追踪产物。
test.use({ trace: 'off', actionTimeout: 10_000 })
test.skip(!endpoint, '设置 WORKSPACE_LIVE_API，连接 tests/support/workspace_server.py 的独立测试实例')
async function choose(page: Page, parent: Locator, label: string, option: string) {
  await parent.getByLabel(label, { exact: true }).click()
  await parent.getByLabel(label, { exact: true }).fill(option)
  await page.locator('.ant-select-dropdown:visible').getByText(option, { exact: true }).click()
  await parent.getByLabel(label, { exact: true }).press('Escape')
}
async function login(page: Page, password: string) {
  await page.getByLabel('登录名', { exact: true }).fill('ui-admin')
  await page.getByLabel('密码', { exact: true }).fill(password)
  await page.getByRole('button', { name: '登录', exact: true }).click()
}

test('真实 IAM/渠道：首次改密、开通、成员双入口、签发和轮换 Key、暂停与归档', async ({ page }) => {
  test.setTimeout(120_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/admin/v1/**', async route => {
    const url = new URL(route.request().url())
    const response = await route.fetch({ url: `${endpoint}${url.pathname}${url.search}` })
    await route.fulfill({ response })
  })
  await page.goto('/')
  await login(page, 'Initial-ui-password-1234')
  await expect(page.getByRole('heading', { name: '修改初始密码' })).toBeVisible()
  await page.getByLabel('当前密码').fill('Initial-ui-password-1234')
  await page.getByLabel('新密码', { exact: true }).fill('Changed-ui-password-5678')
  await page.getByLabel('确认新密码').fill('Changed-ui-password-5678')
  await page.getByRole('button', { name: '修改密码并重新登录' }).click()
  await login(page, 'Changed-ui-password-5678')
  await expect(page.getByRole('heading', { name: '工作台' })).toBeVisible()
  await page.goto('/accounts')
  await page.getByRole('button', { name: '创建账号', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('登录名').fill('ui-member')
  await dialog.getByLabel('初始密码').fill('Member-password-1234')
  await dialog.getByLabel('显示名称').fill('运营测试员')
  await dialog.getByRole('button', { name: '确认', exact: true }).click()
  await expect(dialog).toBeHidden()
  await page.goto('/channels')
  await page.getByRole('button', { name: '开通渠道', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('渠道名称').fill('页面租号渠道')
  await dialog.getByLabel('渠道编码').fill('ui-rental')
  await dialog.getByLabel('负责人').fill('测试负责人')
  await choose(page, dialog, '首位管理员', '页面管理员（ui-admin）')
  await dialog.getByLabel('数据域名称').fill('租号业务域')
  await dialog.getByLabel('外部数据域类型').fill('workspace')
  await dialog.getByLabel('外部数据域编号').fill('source-001')
  await dialog.getByRole('button', { name: '确认', exact: true }).click()
  await expect(dialog).toBeHidden()
  await page.getByRole('link', { name: '页面租号渠道', exact: true }).click()
  const detailPath = new URL(page.url()).pathname
  await page.getByRole('button', { name: '切换工作区' }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByRole('combobox').click()
  await page.locator('.ant-select-dropdown:visible').getByText('页面租号渠道 · 测试 · 租号业务域', { exact: true }).click()
  await dialog.getByRole('button', { name: '进入工作区' }).click()
  await expect(page.getByRole('heading', { name: '工作台' })).toBeVisible()
  await page.goto(detailPath)
  await page.getByRole('tab', { name: '接入服务', exact: true }).click()
  await page.getByRole('button', { name: '登记接入服务', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('名称', { exact: true }).fill('租号业务后端')
  await choose(page, dialog, '环境', '测试')
  await choose(page, dialog, '可调用能力', '执行能力')
  await choose(page, dialog, '业务数据域', '测试 · 租号业务域')
  await dialog.getByRole('button', { name: '确认', exact: true }).click()
  await expect(dialog).toBeHidden()
  await page.getByRole('tab', { name: '接入 Key', exact: true }).click()
  await page.getByRole('button', { name: '创建 Key', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('名称', { exact: true }).fill('租号接入凭据')
  await choose(page, dialog, '环境', '测试')
  await choose(page, dialog, '可调用能力', '执行能力')
  await choose(page, dialog, '接入服务', '租号业务后端 · 测试')
  await dialog.getByLabel('有效期至').fill('2027-10-01T12:00')
  await dialog.getByRole('button', { name: '确认', exact: true }).click()
  const secretInput = page.getByLabel('完整 Key')
  await expect(secretInput).toBeVisible()
  const secret = await secretInput.inputValue()
  expect(secret.length).toBeGreaterThan(30)
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.getByRole('button', { name: '复制 Key' }).click()
  await expect(page.getByRole('button', { name: '已复制' })).toBeVisible()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(secret)
  await page.getByRole('button', { name: '完成', exact: true }).click()
  await expect(page.getByText(secret, { exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => JSON.stringify(sessionStorage))).not.toContain(secret)
  await page.getByRole('button', { name: '归档渠道', exact: true }).click()
  dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: '确认归档渠道' })).toBeDisabled()
  await expect(dialog.getByText(/Key.*吊销|吊销.*Key/)).toBeVisible()
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('tab', { name: '成员与权限', exact: true }).click()
  await page.getByRole('button', { name: '添加成员', exact: true }).click()
  dialog = page.getByRole('dialog')
  await choose(page, dialog, '账号', '运营测试员（ui-member）')
  await choose(page, dialog, '角色', '审计人员')
  await choose(page, dialog, '可用环境', '测试')
  await choose(page, dialog, '业务数据域', '测试 · 租号业务域')
  await dialog.getByRole('button', { name: '确认', exact: true }).click()
  await expect(dialog).toBeHidden()
  await page.goto('/members')
  await expect(page.getByRole('row').filter({ hasText: '运营测试员' })).toBeVisible()
  await page.getByRole('tab', { name: '资源授权', exact: true }).click()
  await page.getByRole('button', { name: '添加授权' }).click()
  dialog = page.getByRole('dialog')
  await choose(page, dialog, '授权对象', '运营测试员')
  await choose(page, dialog, '资源', '页面租号渠道')
  await choose(page, dialog, '可操作动作', '查看操作审计')
  await choose(page, dialog, '可用环境', '测试')
  await choose(page, dialog, '业务数据域', '测试 · 租号业务域')
  await dialog.getByRole('button', { name: '确认', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('row').filter({ hasText: '运营测试员' })).toBeVisible()
  await page.goto(detailPath)
  await page.getByRole('button', { name: '暂停渠道', exact: true }).click()
  await page.getByRole('button', { name: '确认暂停渠道', exact: true }).click()
  await expect(page.getByRole('button', { name: '恢复渠道', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '恢复渠道', exact: true }).click()
  await page.getByRole('button', { name: '确认恢复渠道', exact: true }).click()
  await expect(page.getByRole('button', { name: '暂停渠道', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: '接入 Key', exact: true }).click()
  await page.getByRole('button', { name: '轮换', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('新 Key 有效期至').fill('2027-10-02T12:00')
  await dialog.getByLabel('新旧 Key 重叠时长（秒）').fill('0')
  await dialog.getByRole('button', { name: '确认', exact: true }).click()
  await expect(page.getByLabel('完整 Key')).toBeVisible()
  await page.getByRole('button', { name: '完成', exact: true }).click()
  const activeKey = page.getByRole('row').filter({ hasText: '启用' })
  await activeKey.getByRole('button', { name: '吊销', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '确认', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await page.getByRole('button', { name: '归档渠道', exact: true }).click()
  await page.getByRole('button', { name: '确认归档渠道', exact: true }).click()
  await expect(page.getByText('已归档', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '返回平台', exact: true }).click()
  await expect(page.getByRole('heading', { name: '工作台' })).toBeVisible()
  await page.getByRole('button', { name: '退出登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '登录', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})
